### ISSUE TITLE
Eternal loading screen and no download

### ISSUE THREAD

**Issue by MystaraCorvus** [nilooy/mixamo-animation-combiner#2]
![Capturewda](https://user-images.githubusercontent.com/16919283/92992852-28ac5d80-f4ee-11ea-91f4-ca11010c06cd.PNG)

After I choose the export option its just loading.

I uploaded my files to google drive for testing purpose. 

https://drive.google.com/drive/folders/1xD2xKRdatHIXAwCloVRjxpZq5fz1lGMn?usp=sharing

It can't read the width, strange. 

![Capturewda](https://user-images.githubusercontent.com/16919283/92993301-c1dc7380-f4f0-11ea-86ef-a2c1f36eecac.PNG)

**Comment by nilooy** [comment]
there might be some issue with the model,  the link is asking for request access, I already asked and waiting for approval. Will look into the issue as soon you give me access

**Comment by MystaraCorvus** [comment]
Ok you should have access now.

**Comment by nilooy** [comment]
> Ok you should have access now.

No, it's still asking for access.

**Comment by MystaraCorvus** [comment]
Oh, sorry I missed something. Now you are added.

**Comment by nilooy** [comment]
The problem is actually with the loader as three.js FBXLoader doesn't support psd texture, i tried remove the texture and it works. Have you made the model yourself? if yes, then try to use a jpg or png format for the texture.

I searching a for way to catch the error in the app.

**Comment by MystaraCorvus** [comment]
Okay, no I didn't make it myself. Would a PSD to JPG converter do? 
https://davidwalsh.name/convert-psd-png
There is actually  good way to set something like that up.

**Comment by nilooy** [comment]
Don't worry, I am updating the app in a bit. In the way that you will be able to change the texture or remove it to export it as a valid file.

**Comment by MystaraCorvus** [comment]
Thanks that helps a lot :D Your tool is so great! Thanks for the support.

**Comment by nilooy** [comment]
Can you give a screenshot or link to see how the original model should looks like with texture?

**Comment by MystaraCorvus** [comment]
Oh, sorry didn't saw your message. For me, personally it would be okay without a  texture. It's just the skinless base mesh that i use later for the characters. I am a bit surprised by the whole texture thing because it shouldn't have one.

**Comment by nilooy** [comment]
Ok, i'm deploying tge new version within half an hour

**Comment by nilooy** [comment]
> Oh, sorry didn't saw your message. For me, personally it would be okay without a texture. It's just the skinless base mesh that I use later for the characters. I am a bit surprised by the whole texture thing because it shouldn't have one.
> 
> I guess the texture was generated by base from 3Ds Max or Mixamo.
@MystaraCorvus 
The issue have been solved. New version has been released Now, you can remove the texture to get a valid gltf/glb file

**Comment by MystaraCorvus** [comment]
Okay, after tests it works. The problem with the texture stopping the process is gone. Thanks so much for the help!
